NoteMateSync/app1/urls.py
from django.urls import path
from app1 import views

urlpatterns = [
   path('',views.home,name='home'),
   
   path('notes-view/',views.notesview,name='notesview'),
   path('college/',views.college,name='college'),
   path('club/',views.club,name='club'),
]

NoteMateSync/nms/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app1.urls')),
    path('notes/',include('notesapp.urls',namespace='notesapp'))
    
]

NoteMateSync/notesapp/urls.py
from django.urls import path
from .views import note_view,like_note

app_name = 'notesapp'

urlpatterns = [
    path('',note_view,name='note-list'),
    path('like/',like_note,name='like-note')
    
]

NoteMateSync/app1/models.py
from django.db import models

# Create your models here.

NoteMateSync/notesapp/models.py
from django.db import models
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Note(models.Model):
    title=models.CharField(max_length=50)
    pages=models.IntegerField()
    img=models.ImageField(upload_to='Notes',blank=True,null=True)
    body=models.TextField()
    updated=models.DateTimeField(auto_now=True)
    created=models.DateTimeField(auto_now_add=True)
    liked=models.ManyToManyField(User,default=None,blank=True,related_name='liked')
    author=models.ForeignKey(User,on_delete=models.CASCADE,related_name='author')

    def __str__(self):
        return str(self.title)
    

    @property
    def num_likes(self):
        return self.liked.all().count()
    
LIKE_CHOICES=(
         ('LIKE','LIKE'),
         ('UNLIKE','UNLIKE')
    )

class Like(models.Model):
        user = models.ForeignKey(User,on_delete=models.CASCADE)
        note=models.ForeignKey(Note,on_delete=models.CASCADE)
        value=models.CharField(choices=LIKE_CHOICES,default='LIKE',max_length=10)

        def __str__(self):
            return str(self.note)

    

NoteMateSync/app1/views.py
from django.shortcuts import render


# Create your views here.
def home(request):
    return render(request,'index.html')



def notesview(request):
    return render(request,'notes-view.html')

def college(request):
    return render(request,'college-view.html')

def club(request):
    return render(request,'club.html')

NoteMateSync/notesapp/views.py
from django.shortcuts import render,redirect
from .models import *
# Create your views here.
def note_view(request):
    qs=Note.objects.all()
    user = request.user

    context={
        'qs':qs,
        'user':user,
    }

    return render(request,'notes.html',context)

def like_note(request):
    user = request.user
    if request.method=='POST':
        note_id=request.POST.get('note_id')
        note_obj=Note.objects.get(id=note_id)

        if user in note_obj.liked.all():
            note_obj.liked.remove(user)
        else:
            note_obj.liked.add(user)
        
        like,created=Like.objects.get_or_create(user=user,note_id=note_id)

        if not created:
            if like.value=='Like':
                like.value=='Unlike'
            else:
                like.value='Like'

        like.save()            

            
    return redirect('notesapp:note-list')

NoteMateSync/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Mentor Bootstrap Template - Index</title>
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/animate.css' %}/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Mentor
  * Updated: Mar 10 2023 with Bootstrap v5.2.3
  * Template URL: https://bootstrapmade.com/mentor-free-education-bootstrap-theme/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>
     <!-- ======= Header ======= -->
  <header id="header" class="fixed-top">
    <div class="container d-flex align-items-center">

      <h1 class="logo me-auto"><a href="index.html">Mentor</a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo me-auto"><img src="{% static 'assets/img/logo.png' %}" alt="" class="img-fluid"></a>-->

      <nav id="navbar" class="navbar order-last order-lg-0">
        <ul>
          <li><a class="active" href="/">Home</a></li>
          
          <li><a href="/notes">Notes</a></li>
          <li><a href="courses.html">Community</a></li>
          <li class="dropdown"><a href="#"><span>Pages</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              <li><a href="#">Landing</a></li>
              <li class="dropdown"><a href="#"><span>Deep Drop Down</span> <i class="bi bi-chevron-right"></i></a>
                <ul>
                  <li><a href="#">Deep Drop Down 1</a></li>
                  <li><a href="#">Deep Drop Down 2</a></li>
                  <li><a href="#">Deep Drop Down 3</a></li>
                  <li><a href="#">Deep Drop Down 4</a></li>
                  <li><a href="#">Deep Drop Down 5</a></li>
                </ul>
              </li>
              <li><a href="#">About Us</a></li>
              <li><a href="#">Blog</a></li>
              <li><a href="#">Contact Us</a></li>
              
            </ul>
          </li>

          <li><a href="/notes/notes">Notes</a></li>

          <li class="nav-item dropdown pe-3 d-none">

            <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown" style="min-width:200px">
              <img src="{% static 'assets/img/profile-img.jpg' %}" alt="Profile" class="rounded-circle profile-image">
              <span class="d-none d-md-block dropdown-toggle ps-2">K. Anderson</span>
            </a><!-- End Profile Iamge Icon -->
  
            <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile" style="min-width:200px">
              <li class="dropdown-header">
                <h6>Kevin Anderson</h6>
                <span>Web Designer</span>
              </li>
              <li>
                <hr class="dropdown-divider">
              </li>
  
              <li>
                <a class="dropdown-item d-flex align-items-center" href="users-profile.html">
                  <i class="bi bi-person"></i>
                  <span>My Profile</span>
                </a>
              </li>
              <li>
                <hr class="dropdown-divider">
              </li>
  
              <li>
                <a class="dropdown-item d-flex align-items-center" href="users-profile.html">
                  <i class="bi bi-gear"></i>
                  <span>Account Settings</span>
                </a>
              </li>
              <li>
                <hr class="dropdown-divider">
              </li>
  
              <li>
                <a class="dropdown-item d-flex align-items-center" href="pages-faq.html">
                  <i class="bi bi-question-circle"></i>
                  <span>Need Help?</span>
                </a>
              </li>
              <li>
                <hr class="dropdown-divider">
              </li>
  
              <li>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <i class="bi bi-box-arrow-right"></i>
                  <span>Sign Out</span>
                </a>
              </li>
  
            </ul><!-- End Profile Dropdown Items -->
          </li>


        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

      <a href="/auth/signup/" class="get-started-btn c-gradient">Get Started</a>
      <!-- <a href="/auth/login/" class="get-started-btn c-gradient">Login</a> -->

    </div>
  </header><!-- End Header -->
  {% block content %}{% endblock content %}

  <!-- ======= Footer ======= -->
  <footer id="footer">

    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-contact">
            <h3>Mentor</h3>
            <p>
              A108 Adam Street <br>
              New York, NY 535022<br>
              United States <br><br>
              <strong>Phone:</strong> +1 5589 55488 55<br>
              <strong>Email:</strong> info@example.com<br>
            </p>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Our Services</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
            </ul>
          </div>

          <div class="col-lg-4 col-md-6 footer-newsletter">
            <h4>Join Our Newsletter</h4>
            <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
            <form action="" method="post">
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form>
          </div>

        </div>
      </div>
    </div>

    <div class="container d-md-flex py-4">

      <div class="me-md-auto text-center text-md-start">
        <div class="copyright">
          &copy; Copyright <strong><span>Mentor</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
          <!-- All the links in the footer should remain intact. -->
          <!-- You can delete the links only if you purchased the pro version. -->
          <!-- Licensing information: https://bootstrapmade.com/license/ -->
          <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/mentor-free-education-bootstrap-theme/ -->
          Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
      </div>
      <div class="social-links text-center text-md-right pt-3 pt-md-0">
        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
        <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

<script src="https://code.jquery.com/jquery-3.7.0.min.js" integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>


  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>
  <script src="{% static 'assets/js/script.js' %}"></script>


</body>
</html>

NoteMateSync/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex justify-content-center align-items-center">
  <div class="hero-bg " style="height:100%; width:100%; margin:30px 10px 10px 10px; border-radius:50px; background: #212529;">
    <div class="container position-relative " data-aos="zoom-in" data-aos-delay="100">
      <div class="row align-items-center ">
        <div class="col-7" style="margin-top:-110px;">
        <!-- <p>Best Online Platform</p> -->
          <h1>Learning Today,<br>Leading Tomorrow</h1>
          <h2>We are team of talented designers making websites with Bootstrap</h2>
        </div>
        <div class="col-5">
          <img src="{% static 'assets/img/hero-banner.webp' %}" alt="banner" style="height:100%; width:95%;">
        </div>
      </div>
        
    </div>
  </div>
</section><!-- End Hero -->

<main id="main">

  

  <!-- ======= Counts Section ======= -->
  <section id="counts" class="counts section-bg">
    <div class="container">

      <div class="row counters">

        <div class="col-lg-3 col-6 text-center">
          <span data-purecounter-start="0" data-purecounter-end="1232" data-purecounter-duration="1" class="purecounter"></span>
          <p>Students</p>
        </div>

        <div class="col-lg-3 col-6 text-center">
          <span data-purecounter-start="0" data-purecounter-end="64" data-purecounter-duration="1" class="purecounter"></span>
          <p>Courses</p>
        </div>

        <div class="col-lg-3 col-6 text-center">
          <span data-purecounter-start="0" data-purecounter-end="42" data-purecounter-duration="1" class="purecounter"></span>
          <p>Events</p>
        </div>

        <div class="col-lg-3 col-6 text-center">
          <span data-purecounter-start="0" data-purecounter-end="15" data-purecounter-duration="1" class="purecounter"></span>
          <p>Trainers</p>
        </div>

      </div>

    </div>
  </section><!-- End Counts Section -->

  <!--Special Features Section-->
  <section  class="">
    <div class="container">
      <div class="row">
        <div class="col-4">
          <h1 class="fw-bold">Our <span class="c-p-color">Features </span><br> Special For You</h1>
          <p>Lorem Ipsum is simply dummy text of the printing</p>
          <a href="#" class="c-btn">View All<i class="bi bi-arrow-right-circle ps-3"></i></a>

        </div>
        <div class="col-8">
          <div class="row">
            <div class="col-4">

            </div>
            <div class="col-4">
              
            </div>
            <div class="col-4">
              
            </div>
          </div>
        </div>
      </div>
    </div>
  </section><!--End Special Features Section-->

  <!--Section 3-->
  <section>
    <div class="container">
      <div class="row">
        <div class="col-6">

        </div>
        <div class="col-6">
          <h1 class="fw-bold">Our <span class="c-p-color">Features </span><br> Special For You</h1>
          <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
          <a href="#" class="c-btn">View All<i class="bi bi-arrow-right-circle ps-3"></i></a>
        </div>
      </div>
    </div>
  </section>

  <!--Why Choose US Section -->
  <section>
    <div class="container">
      <div class="row">
        <div class="col-6">
          <div class="row">
            <h1 class="fw-bold">Why Choose Us Our<br>Learning<span class="c-p-color"> Platform</span></h1>
          </div>
          <div class="row">
            <div class="col-6 my-3">
              <img src="{% static 'assets/img/profile-img.jpg' %}" alt="icon" class="rounded-circle mb-3" style="height:60px; width:60px;">
              <h2 class="fw-semibold">Heading 1</h2>
              <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
            </div>

            <div class="col-6 my-3">
              <img src="{% static 'assets/img/profile-img.jpg' %}" alt="icon" class="rounded-circle mb-3" style="height:60px; width:60px;">
              <h2 class="fw-semibold">Heading 2</h2>
              <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
            </div>

            <div class="col-6 my-3">
              <img src="{% static 'assets/img/profile-img.jpg' %}" alt="icon" class="rounded-circle mb-3" style="height:60px; width:60px;">
              <h2 class="fw-semibold">Heading 3</h2>
              <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
            </div>

            <div class="col-6 my-3">
              <img src="{% static 'assets/img/profile-img.jpg' %}" alt="icon" class="rounded-circle mb-3" style="height:60px; width:60px;">
              <h2 class="fw-semibold">Heading 4</h2>
              <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
            </div>
          </div>
        </div>
        <div class="col-6">
          
        </div>
      </div>
    </div>
  </section><!--End Why Choose US Section -->


  <section><!--College List Section-->
    <div class="container">
      <div class="row text-center">
        <h1 class="fw-bold">Why Choose Us Our Learning<span class="c-p-color"><br>Platform</span></h1>
        <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
        <div class="col-12 college-container-radius mt-4">
          <div class="row">
            <div class="col-12 college-container">

            </div>
          </div>

        </div>
      </div>
    </div>
  </section><!--End College List Section-->

  <section><!--FAQs Section-->
    <div class="container">
      <div class="row text-center">
        <h1 class="mb-2 fw-bold">Frequently Asked Questions</h1>
        <hr style="border-top: 3px solid #8224E3; margin-top: 20px; margin-bottom: 20px; width: 5%; margin:auto; boder-radius:10px;">
        <div class="col-12 mt-4">
         <div class="row">
           <div class="col-5">

           </div>
           <div class="col-2">
            <svg xmlns="http://www.w3.org/2000/svg" width="17" height="602" viewBox="0 0 17 602" fill="none">
              <path d="M8.90278 9.05991e-06C4.48451 -0.00670564 0.897349 3.56957 0.890634 7.98784C0.883919 12.4061 4.46019 15.9933 8.87847 16C13.2967 16.0067 16.8839 12.4304 16.8906 8.01216C16.8973 3.59388 13.3211 0.00672376 8.90278 9.05991e-06ZM8.01221 586C3.59393 585.993 0.00677096 589.57 5.62662e-05 593.988C-0.00665843 598.406 3.56962 601.993 7.98789 602C12.4062 602.007 15.9933 598.431 16 594.012C16.0068 589.594 12.4305 586.007 8.01221 586ZM7.39063 7.99772L6.50005 593.998L9.50005 594.002L10.3906 8.00228L7.39063 7.99772Z" fill="#8224E3"/>
            </svg>
           </div>
           <div class="col-5">

           </div>
         </div>

        </div>
      </div>
    </div>
  </section><!--End FAQs Section-->


  <section><!--College List Section-->
    <div class="container">
      <div class="row">
        
      </div>
    </div>
  </section><!--End College List Section-->



</main><!-- End #main -->



{% endblock content %}

NoteMateSync/templates/notes.html
{% extends 'base.html' %}
{% load static  %}
{% block content %}
<div class="container" style="padding-top:100px;">

    <!-- search notes form   -->
    <form>
      <div class="input-group c-search p-2 mb-4 ">
        <i class="bi bi-search mx-3 mt-2"></i>
        <input type="text" class="form-control " placeholder="Search Notes" aria-label="Recipient's username"
          aria-describedby="button-addon2">
          <span style="height: 25px; background-color: #c7c7c7; width: 3px; border-radius: 5px; margin-top: 6px;" class="mx-2"> </span>
        <button class="btn btn-outline-secondary c-search-btn ms-2 px-5" type="button" id="button-addon2">Search</button>
      </div>
    </form>

    <!-- Dropdown button  -->
    <div class="row justify-content-start">
      <div class="col-auto">
        <select class="form-select c-select py-2" aria-label="Default select example">
          <option selected>Institute</option>
          <option value="1">One</option>
          <option value="2">Two</option>
          <option value="3">Three</option>
        </select>
      </div>

      <div class="col-auto">
        <select class="form-select c-select py-2" aria-label="Default select example">
          <option selected>Open this select menu</option>
          <option value="1">One</option>
          <option value="2">Two</option>
          <option value="3">Three</option>
        </select>
      </div>

      <div class="col-auto">
        <select class="form-select c-select py-2" aria-label="Default select example">
          <option selected>Open this select menu</option>
          <option value="1">One</option>
          <option value="2">Two</option>
          <option value="3">Three</option>
        </select>
      </div>
    </div>
  </div>
  <!-- Dropdown button End  -->

  <hr>

  <!-- Notes Card Main Container  -->
  <div class="container my-3">
    <div class="row">
      <!-- Notes List Container  -->
      <div class="col-lg-9 pt-3 px-4" style="background-color: #fff; border: 1px solid #d7dde0; border-radius: 10px;">
        <div class="row justify-content-end ">
          <div class="col-auto">
            <select class="form-select c-select c-select2 py-2" aria-label="Default select example">
              <option selected>Open this select menu</option>
              <option value="1">One</option>
              <option value="2">Two</option>
              <option value="3">Three</option>
            </select>
          </div>
        </div>

        <div class="row">
          {% for obj in qs%}
        <!--  notes card -->
          <div class="col-lg-4 col-md-6">
            <div class="card mt-3" style="border-radius: 15px; overflow: hidden;">
              <!-- Thumbnail image -->
              <img src="{{Notes.img.url}}" class="card-img-top" alt="...">
              <hr>
              <div class="card-body py-0 pb-3">
                <div class="d-inline-flex py-2 px-3 mb-3" style="font-size: 0.85rem; background-color: hsla(0, 0%, 86%, 0.3); border-radius: 5px; color: #4886FF;">
                  <span><i class="bi bi-file-earmark-pdf"></i></span>
                  <!--Page Number-->
                  <span class="ms-2" >{{obj.page}}</span>
                </div>
                <!-- Title -->
                <h5 class="card-title fw-semibold">{{obj.title}}</h5>
                <!-- Subject Name -->
                <p class="card-text" style="color: #4886FF;">{{obj.course}}</p>
                <hr>
                <div class="mb-2" style="color: #848484;">
                  <span><i class="bi bi-file-earmark-pdf"></i></span>
                  <!-- Institude Name -->
                  <span class="ms-2 fs-6">{{obj.college}}</span>
                </div>
                
                <div class="d-inline-flex mb-2" style="color: #848484;">
                  <span><i class="bi bi-calendar"></i></span>
                  <!-- Date -->
                  <span class="ms-2 fs-6">{{obj.created}}</span>
                </div>
                <form action="{% url 'notesapp:like-note' %}" method='POST'>
                  {% csrf_token %}
                  <input type="hidden" name='note_id' value={{obj.id}}>
                  {% if user not in obj.liked.all %}
                  <span><button class="ui button positive" type='submit'>Like</button></span>
                  {% else %}
                  <span><button class="ui button negative" type='submit'>Unlike</button></span>
                  {% endif %} 
                </form>
                <strong>{{obj.liked.all.count}} Likes</strong>
                <div class="d-inline-flex ms-2 mb-2" style="color: #848484;">
                  <span><i class="bi bi-hand-thumbs-up-fill"></i></span>
                  <!-- Like -->
                  <span class="ms-2 fs-6"></span>
                </div>

                <div class="d-inline-flex ms-2 mb-2" style="color: #848484;">
                  <span><i class="bi bi-chat"></i></span>
                  <!-- Comments -->
                  <span class="ms-2 fs-6">69</span>
                </div>
              </div>

            </div>
          </div> <!--  #notes card end-->
          {% endfor %}

          
        </div>


        <div class="row my-3 justify-content-center">
          <div class="col-auto ">
            <nav aria-label="...">
              <ul class="pagination">
                <li class="page-item disabled">
                  <a class="page-link">Previous</a>
                </li>
                <li class="page-item"><a class="page-link" href="#">1</a></li>
                <li class="page-item active" aria-current="page">
                  <a class="page-link" href="#">2</a>
                </li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item">
                  <a class="page-link" href="#">Next</a>
                </li>
              </ul>
            </nav>
          </div>
        </div>
      </div>

      <div class="col-lg-3" style="height:800px;">

      </div>
    </div>
    
  </div>
{% endblock content %}